### ISSUE TITLE
Status of  pico2wave?

### ISSUE THREAD

**Issue by HawkingJan** [skiwithpete/alarmpi#12]
I'm a bit confused about the support of pico2wave.
In the readme it is stated 
"For pico2wave support (this does not work as of 2016/03/13, but may work in the future "
but at the bottom
"Thanks to Craig Pennington for adding pico2wave support".

I just did 
`sudo apt-get install festival libttspico-utils
`and then 
`pico2wave -w Test.wav "A short test" ; mplayer Test.wav; rm Test.wav`
worked out of the box without any compilation needed (I'm using a Raspi running Raspbian Jessie).

But if set

```
[trygoogle]
enabled=0

....
[trypico2wave]
enabled=1
```

I get

```
Traceback (most recent call last):
  File "./sound_the_alarm.py", line 42, in <module>
    raise ImportError('Failed to load '+section)
ImportError: Failed to load trypico2wave

```

And as far as I can see, there is a file 
 get_trygoogle.py and one  get_tryivona.py but no get_trypico2wave .
I used git clone https://github.com/skiwithpete/alarmpi
As there is already the section in the alarm.config and the thanks in the Readme and pico2wave works I wonder why the last step is missing (for me it looks like a very simple module but maybe I don't see some complications)? I would really appreciate to use the TTS locally with pico2wave.

**Comment by cpenning** [comment]
Sorry, the main ivona file was missing from my original commit.
