### ISSUE TITLE
GOOGLE TTS

### ISSUE THREAD

**Issue by yaskad** [skiwithpete/alarmpi#5]
Hello!
First of all, I would like to thank you for your awesome project! I've been using it for months now, but lately I've had some issues with google tts. I'm not reciving mp3 back, I googled about the problem and it seems that google tts is a lot restricted now, I've tried to enter the "captcha", so that my rpi is recognized by google but it didn't work. I'm wondering if you have similar issue? Or if you know a way to work around it. 

I'm very thankful for answers.

**Comment by neondemon** [comment]
change &clint=t to '&client=tw-ob

**Comment by cpenning** [comment]
neondemon's fix works for me: [https://translate.google.com/translate_tts?tl=en&q=hello+world&client=tw-ob](https://translate.google.com/translate_tts?tl=en&q=hello+world&client=tw-ob)
